---
name: CICD-base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CICD-base:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      # Checkout codebase
      - name: Checkout
        uses: actions/checkout@v5

      # Run CICD-base
      - name: CICD-base
        uses: docker://ghcr.io/uclahs-cds/cicd-base:dev
        env:
          VALIDATE_DOCKERFILE: false
